export const featuredProjects = [
  {
    number: "01",
    category: "PLATAFORMA WEB",
    name: "Klipp",
    slug: "klipp",
    description: "Experiencia digital para gestionar sesiones, beneficios y comunicaciones con clientes.",
    problem: "La operacion necesitaba ordenar informacion de usuarios y acciones frecuentes en un flujo simple.",
    solution: "Se desarrollo una interfaz clara para centralizar accesos, sesiones y datos clave del servicio.",
    scope: "Web app - Panel - Gestion de usuarios - Experiencia cliente",
    outcome: "Gestion mas rapida, trazable y facil de usar.",
    metrics: ["Inicio de sesion", "Perfil cliente", "Beneficios"],
    technologies: ["Astro", "TypeScript", "UI responsive", "APIs"],
    image: "/images/projects/project-klipp-landing-2.png",
    imageAlt: "Pantalla de sesion del proyecto Klipp",
    published: true,
    featured: true,
    isDemo: false,
  },
  {
    number: "02",
    category: "SISTEMA ADMINISTRATIVO",
    name: "El Pueblo",
    slug: "botica",
    description: "Panel para controlar ventas, inventario, compras y actividad diaria de la botica.",
    problem: "El control de productos y movimientos dependia de registros dispersos y revision manual.",
    solution: "Se implemento un dashboard operativo con accesos a inventario, compras y seguimiento comercial.",
    scope: "Dashboard - Inventario - Compras - Reportes",
    outcome: "Mejor visibilidad de stock, compras y operaciones.",
    metrics: ["Dashboard", "Inventario", "Compras"],
    technologies: ["Astro", "TypeScript", "Panel admin", "Datos operativos"],
    image: "/images/projects/project-botica-landing-3.png",
    imageAlt: "Dashboard administrativo del proyecto El Pueblo",
    published: true,
    featured: true,
    isDemo: false,
  },
  {
    number: "03",
    category: "SMS Y RECARGAS",
    name: "SMS Fortuna",
    slug: "fortuna",
    description: "Landing y sistema operativo para gestionar servicios SMS, recargas y backoffice.",
    problem: "El servicio necesitaba presentar su oferta y ordenar operaciones internas desde un entorno digital.",
    solution: "Se construyo una landing clara y pantallas de gestion para recargas, clientes y administracion.",
    scope: "Landing - Backoffice - Recargas - Gestion operativa",
    outcome: "Servicio mas visible y operacion interna mas ordenada.",
    metrics: ["Landing", "Backoffice", "Recargas"],
    technologies: ["Astro", "TypeScript", "UI responsive", "Panel admin"],
    image: "/images/projects/project-sms-fortuna-landing-1.png",
    imageAlt: "Backoffice del proyecto SMS Fortuna",
    published: true,
    featured: true,
    isDemo: false,
  },
];
