export const featuredProjects = [
  {
    number: "01",
    category: "SOFTWARE A MEDIDA",
    name: "Nexo Operativo",
    slug: "nexo-operativo",
    description: "Plataforma para centralizar clientes, operaciones y seguimiento en un solo sistema.",
    problem: "La empresa gestionaba informacion mediante archivos separados y procesos manuales.",
    solution: "Se desarrollo una plataforma central con usuarios, permisos, registros y reportes.",
    scope: "Aplicacion web · Panel administrativo · Integraciones · Infraestructura",
    technologies: ["Astro", "Node.js", "PostgreSQL", "APIs"],
    image: "/images/projects/nexo-operativo.svg",
    imageAlt: "Mockup provisional de plataforma administrativa para gestionar operaciones",
    published: true,
    featured: true,
    isDemo: true,
  },
  {
    number: "02",
    category: "AUTOMATIZACION",
    name: "Flujo Comercial",
    slug: "flujo-comercial",
    description: "Sistema de formularios, notificaciones y agenda para ordenar solicitudes comerciales.",
    problem: "Los leads llegaban por distintos canales y el seguimiento dependia de mensajes manuales.",
    solution: "Se conectaron formulario, API, CRM, WhatsApp y calendario en un flujo trazable.",
    scope: "Landing · API · CRM · WhatsApp · Calendario",
    technologies: ["Astro", "TypeScript", "Webhooks", "CRM"],
    image: "/images/projects/flujo-comercial.svg",
    imageAlt: "Mockup provisional de flujo automatizado entre formulario, CRM y calendario",
    published: true,
    featured: true,
    isDemo: true,
  },
];

