export const featuredProjects = [
  {
    number: "01",
    category: "SOFTWARE A MEDIDA",
    name: "Nexo Operativo",
    slug: "nexo-operativo",
    description: "Clientes, operaciones y reportes centralizados en una sola plataforma.",
    problem: "Información distribuida y seguimiento manual.",
    solution: "Usuarios, procesos y registros en una plataforma central.",
    scope: "Web app - Admin - Integraciones - Infraestructura",
    outcome: "Mayor control y trazabilidad operativa.",
    metrics: ["Panel central", "Roles y permisos", "Reportes"],
    technologies: ["Astro", "Node.js", "PostgreSQL", "APIs"],
    image: "/images/projects/nexo-operativo.svg",
    imageAlt: "Captura del producto Nexo Operativo con panel administrativo",
    published: true,
    featured: true,
    isDemo: true,
  },
  {
    number: "02",
    category: "AUTOMATIZACIÓN",
    name: "Flujo Comercial",
    slug: "flujo-comercial",
    description: "Formulario, CRM, WhatsApp y calendario conectados para vender sin perder leads.",
    problem: "Leads en varios canales y seguimiento manual.",
    solution: "Flujo trazable con alertas y agenda conectada.",
    scope: "Landing - API - CRM - WhatsApp - Calendario",
    outcome: "Seguimiento más rápido y ordenado.",
    metrics: ["CRM conectado", "Alertas", "Agenda"],
    technologies: ["Astro", "TypeScript", "Webhooks", "CRM"],
    image: "/images/projects/flujo-comercial.svg",
    imageAlt: "Captura del producto Flujo Comercial con automatización de leads",
    published: true,
    featured: true,
    isDemo: true,
  },
];
