export const pricingPlans = [
  {
    name: "Esencial",
    price: "S/99",
    period: "/ mes",
    description: "Todo lo necesario para empezar online.",
    cta: "Elegir Esencial",
    message: "Hola Kuroki, quiero elegir el plan Esencial de Landings.",
    permanence: "12 meses de permanencia",
    features: [
      "Landing one-page personalizada",
      "Diseño responsive",
      "Dominio + hosting + SSL",
      "WhatsApp o formulario",
      "SEO básico",
      "Analytics",
      "Animaciones básicas",
      "Copias de seguridad",
      "Mantenimiento técnico",
      "Hasta 30 min de cambios / mes",
    ],
  },
  {
    name: "Negocio",
    price: "S/149",
    period: "/ mes",
    description: "Mide, optimiza y conecta tu web.",
    cta: "Empezar",
    message: "Hola Kuroki, quiero empezar con el plan Negocio de Landings.",
    permanence: "12 meses de permanencia",
    recommended: true,
    features: [
      "Sitio multipágina",
      "Todo lo incluido en Esencial",
      "Animaciones avanzadas",
      "Tracking de conversiones",
      "1 integración",
      "Optimización de rendimiento",
      "Hasta 1 h de cambios / mes",
      "Soporte prioritario",
    ],
  },
  {
    name: "Pro",
    price: "S/199",
    period: "/ mes",
    description: "Más integración y capacidad para evolucionar.",
    cta: "Elegir Pro",
    message: "Hola Kuroki, quiero elegir el plan Pro de Landings.",
    permanence: "12 meses de permanencia",
    features: [
      "Todo lo incluido en Negocio",
      "Hasta 3 integraciones",
      "Integraciones avanzadas con APIs o automatizaciones",
      "Optimización avanzada de rendimiento",
      "Revisión de conversiones",
      "Hasta 2 h de cambios / mes",
    ],
  },
] as const;

export const pricingComparisonRows = [
  {
    feature: "Mensualidad",
    esencial: "S/99",
    negocio: "S/149",
    pro: "S/199",
  },
  {
    feature: "Estructura",
    esencial: "Landing one-page",
    negocio: "Sitio multipágina",
    pro: "Sitio multipágina",
  },
  {
    feature: "Diseño personalizado",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Dominio + hosting + SSL",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Responsive",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "WhatsApp / formulario",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "SEO básico",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Analytics",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Animaciones",
    esencial: "Básicas",
    negocio: "Avanzadas",
    pro: "Avanzadas",
  },
  {
    feature: "Tracking conversiones",
    esencial: "—",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Integraciones",
    esencial: "—",
    negocio: "1",
    pro: "Hasta 3",
  },
  {
    feature: "Copias de seguridad",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Mantenimiento técnico",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Optimización de rendimiento",
    esencial: "—",
    negocio: "✓",
    pro: "Avanzada",
  },
  {
    feature: "Cambios mensuales",
    esencial: "Hasta 30 min de cambios / mes",
    negocio: "Hasta 1 h de cambios / mes",
    pro: "Hasta 2 h de cambios / mes",
  },
  {
    feature: "Soporte",
    esencial: "Estándar",
    negocio: "Prioritario",
    pro: "Prioritario",
  },
  {
    feature: "Permanencia",
    esencial: "12 meses",
    negocio: "12 meses",
    pro: "12 meses",
  },
] as const;
