export const pricingPlans = [
  {
    name: "Esencial",
    price: "S/99",
    period: "/ mes",
    description: "Para empezar con una presencia profesional y clara.",
    cta: "Elegir Esencial",
    message: "Hola Kuroki, quiero elegir el plan Esencial de Landings.",
    permanence: "12 meses de permanencia",
    features: [
      "Landing personalizada",
      "Hosting + SSL",
      "SEO básico",
      "Analytics",
      "Hasta 30 min de ajustes / mes",
    ],
  },
  {
    name: "Negocio",
    price: "S/149",
    period: "/ mes",
    description: "Para negocios que necesitan medir, optimizar y conectar.",
    cta: "Empezar",
    message: "Hola Kuroki, quiero empezar con el plan Negocio de Landings.",
    permanence: "12 meses de permanencia",
    recommended: true,
    features: [
      "Landing personalizada",
      "Hosting + SSL",
      "Tracking de conversiones",
      "1 integración",
      "Hasta 1 h de ajustes / mes",
      "Soporte prioritario",
    ],
  },
  {
    name: "Pro",
    price: "S/199",
    period: "/ mes",
    description: "Para proyectos que necesitan más soporte e integraciones.",
    cta: "Elegir Pro",
    message: "Hola Kuroki, quiero elegir el plan Pro de Landings.",
    permanence: "12 meses de permanencia",
    features: [
      "Landing personalizada",
      "Hosting + SSL",
      "Tracking de conversiones",
      "Integraciones avanzadas",
      "Hasta 2 h de ajustes / mes",
      "Soporte prioritario",
    ],
  },
] as const;

export const pricingComparisonRows = [
  {
    feature: "Mensualidad",
    esencial: "S/99",
    negocio: "S/149",
    pro: "S/199",
  },
  {
    feature: "Landing personalizada",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Hosting + SSL",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Responsive",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "WhatsApp / formulario",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "SEO básico",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Analytics",
    esencial: "✓",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Animaciones",
    esencial: "Básicas",
    negocio: "Avanzadas",
    pro: "Avanzadas",
  },
  {
    feature: "Tracking conversiones",
    esencial: "—",
    negocio: "✓",
    pro: "✓",
  },
  {
    feature: "Integraciones",
    esencial: "—",
    negocio: "1",
    pro: "Por definir",
  },
  {
    feature: "Cambios mensuales",
    esencial: "Hasta 30 min de ajustes / mes",
    negocio: "Hasta 1 h de ajustes / mes",
    pro: "Hasta 2 h de ajustes / mes",
  },
  {
    feature: "Soporte",
    esencial: "Estándar",
    negocio: "Prioritario",
    pro: "Prioritario",
  },
  {
    feature: "Permanencia",
    esencial: "12 meses",
    negocio: "12 meses",
    pro: "12 meses",
  },
] as const;
